# Generated by Django 5.1.1 on 2025-08-27 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='source',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('MELLI', 'Melli'), ('SADERAT', 'Saderat'), ('MELLAT', 'Mellat')], default='UNKNOWN', max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='source',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('MELLI', 'Melli'), ('SADERAT', 'Saderat'), ('MELLAT', 'Mellat')], default='UNKNOWN', max_length=32),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='source',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('MELLI', 'Melli'), ('SADERAT', 'Saderat'), ('MELLAT', 'Mellat')], default='UNKNOWN', max_length=32),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Card number must be 16 digits')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_code',
            field=models.CharField(help_text='10-digit national identification code', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'National code must be 10 digits')]),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number')]),
        ),
        migrations.AddIndex(
            model_name='creditcard',
            index=models.Index(fields=['card_number', 'source'], name='idx_creditcard_number_source'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['national_code', 'source'], name='idx_person_natcode_source'),
        ),
        migrations.AddIndex(
            model_name='phonenumber',
            index=models.Index(fields=['number', 'source'], name='idx_phonenumber_number_source'),
        ),
        migrations.AddConstraint(
            model_name='creditcard',
            constraint=models.UniqueConstraint(fields=('card_number', 'source'), name='uniq_creditcard_number_source'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('national_code', 'source'), name='uniq_person_national_code_source'),
        ),
        migrations.AddConstraint(
            model_name='phonenumber',
            constraint=models.UniqueConstraint(fields=('number', 'source'), name='uniq_phonenumber_number_source'),
        ),
    ]
