# Generated by Django 5.1.1 on 2025-08-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_creditcard_source_person_source_phonenumber_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
