# Generated by Django 5.1.1 on 2025-08-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_person_last_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='phonenumber',
            name='uniq_phonenumber_number_source',
        ),
        migrations.RemoveIndex(
            model_name='phonenumber',
            name='idx_phonenumber_number_source',
        ),
        migrations.AddIndex(
            model_name='phonenumber',
            index=models.Index(fields=['number', 'person', 'source'], name='idx_phone_num_per_src'),
        ),
        migrations.AddConstraint(
            model_name='phonenumber',
            constraint=models.UniqueConstraint(fields=('number', 'person', 'source'), name='uniq_phonenumber_number_person_source'),
        ),
    ]
